version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      TZ: America/Fortaleza
    ports:
      - "3306:3306" # exposto apenas em ambiente de desenvolvimento
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - db_data:/var/lib/mysql
      - C:/Users/Daniel/Desktop/PROJETO-PI/init:/docker-entrypoint-initdb.d

volumes:
  db_data:
